### ISSUE TITLE
Overrides depreciated API

### ISSUE THREAD

**Issue by radha1990kumari** [am15h/tflite_flutter_plugin#132]
```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter-0.8.0\android\src\main\java\com\tfliteflutter\tflite_flutter_plugin\TfliteFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by CaptainDario** [comment]
This should actually already be solved with #37

**Comment by radha1990kumari** [comment]
@CaptainDario but I am still getting this , so what can be potential causes

**Comment by CaptainDario** [comment]
As I am not a maintainer of this package I am not sure.
However you could try v0.9.0 ?

@am15h is this deprecation message a new one or related to #37 ?

**Comment by radha1990kumari** [comment]
@am15h please fix this depreciation issue, I am not able to build release apk due to this .
```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter-0.9.0\android\src\main\java\com\tfliteflutter\tflite_flutter_plugin\TfliteFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
